### PR TITLE
WIP - References

### PR DESCRIPTION
**Pull request by TimTaylor**
This PR aims to achieve two main things:

1. Ensure that all references in the documentation built from R/data.R are up to date and match with the encoded value sets.
2. Add DOI's to the dataframe returned by `valuesets()`.

Currently a work in progress - will flag when ready to review.

### CODE REVIEW

**Comment by TimTaylor** [comment]
It seems like a lot of the VAS value sets do not have DOIs available. I've ensured that the papers reference are included in the R/data.R documentation.

**Comment by TimTaylor** [comment]
Struggling to find a paper to cite for the reverse cross-walk (RCW) value sets.

**Comment by fragla** [comment]
@TimTaylor I think this could be the reference for the reverse crosswalk value sets. I've also included a link to the EuroQol twitter thread where I found it mentioned. 

https://www.sciencedirect.com/science/article/pii/S1098301521001704 https://twitter.com/EuroQol/status/1397145337991663616

**Comment by TimTaylor** [comment]
> @TimTaylor I think this could be the reference for the reverse crosswalk value sets. I've also included a link to the EuroQol twitter thread where I found it mentioned.
> 
> https://www.sciencedirect.com/science/article/pii/S1098301521001704 https://twitter.com/EuroQol/status/1397145337991663616

Cheers - I've taken a look but it's not clear at the moment that this is what is given on the EuroQol site (via stata files) which I think is where the RCW came from. The paper alludes to earlier mappings from EuroQol. Will try and dig in to this some more.

**Comment by fragla** [comment]
I'll drop EuroQol an email to see if they can help/advise.

**Comment by TimTaylor** [comment]
@fragla - Missing a few DOI and PubMed numbers but overall I think this is ready for review. Main changes:

- references have been added in both `data-raw/references.csv` and within the documentation (`R/data.R`) to ensure they match and we have as much coverage as possible.
- The `data` folder has been dropped in favour of only internal data that is exported where necessary (exported within `R/data.R`).
- A `raw-data` folder has been added that holds all of the valuesets and references as csvs. The idea here is that when you want to add a value set or reference you now only need to alter stuff in this folder. It is not used by R so is added to `.Rbuildignore`. The folder also contains a small script `raw-data/save-data.R` that is used to generate the internal data when needed. It also creates the `STATES` list at the same time.
- The `valuesets()` function now merges the result on a `REFERENCES` table to add DOI and PubMed numbers. Currently I'm dropping the url but we may want to change this.

I've played with the shiny app to ensure that has not broken but it is probably worth you double checking that the previous issue you fixed has not regressed. Hope this all makes sense; let me know if not.

**Review by fragla — APPROVED** [review]
One minor tweak of version in DESCRIPTION. Otherwise all good. Will merge into master.

**Pull request merged**
